server.port=8082
server.servlet.context-path=/ski-resort

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

spring.jackson.time-zone=Europe/Moscow

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.cache.cache-names=user
spring.cache.caffeine.spec=initialCapacity=100,maximumSize=500,expireAfterAccess=9h,recordStats